# Generated by Django 4.2 on 2024-02-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_email',
            field=models.EmailField(blank=True, default=models.EmailField(max_length=254, unique=True, verbose_name='Личная почта'), max_length=254, null=True, verbose_name='Рабочая почта'),
        ),
    ]
