# Generated by Django 4.2 on 2024-02-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_work_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Рабочая почта'),
        ),
    ]
