# Generated by Django 4.2 on 2024-02-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_work_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='NoName', max_length=50, unique=True, verbose_name='Компания'),
        ),
    ]
