# Generated by Django 4.2 on 2024-02-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
