# Generated by Django 4.2 on 2024-02-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='NoName', max_length=50, verbose_name='Компания'),
        ),
    ]
