# Generated by Django 4.2 on 2024-02-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_options_user_is_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_blocked', 'can_blocked_user')]},
        ),
    ]
