# Generated by Django 4.2 on 2024-02-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО клиента')),
                ('comments', models.CharField(max_length=200, verbose_name='Комментарии')),
                ('slug', models.CharField(blank=True, default='djangodbmodelsfieldscharfield', max_length=150, null=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиента',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default='9:00', verbose_name='время рассылки')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('regularity', models.CharField(choices=[('once_a_day', 'Раз в день'), ('once_a_week', 'Раз в неделю'), ('once_a_month', 'Раз в месяц')], default='once_a_day', verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'создана'), ('in_work', 'в работе'), ('stopped', 'остановлена')], default=('created', 'создана'), max_length=50, verbose_name='Статус')),
                ('client', models.ManyToManyField(to='mailing_services.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Рассылка для клиентов',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Тема email')),
                ('body', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('status', models.CharField(choices=[('Success', 'успешно'), ('Failure', 'отказ')], max_length=100, verbose_name='Статус попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_services.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'лог отправки письма',
                'verbose_name_plural': 'логи отправок писем',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_services.message', verbose_name='Сообщение'),
        ),
    ]
