# Generated by Django 4.2 on 2024-02-05 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_services', '0002_client_proprietor_mailing_proprietor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='finish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
        ),
    ]
